### ISSUE TITLE
Is there implemented block cementing?

### ISSUE THREAD

**Issue by AlexeyAB** [nanocurrency/nano-node#1018]
Is there implemented block cementing, or when it will be implemented?

https://github.com/nanocurrency/raiblocks/wiki/Attacks#50-attack---low-risk-completely-destructive

> A final line of defense that has not yet been implemented is block cementing.

**Comment by renesq** [comment]
Block cementing refers to irreversible blocks. That is not implemented yet.
If you need transaction finality, you need to monitor the voting status, or simply wait some seconds and look if the block is still in the checked blocks.
There's also the quorum setting in config.json - this will make callback only call your API after a certain vote % is reached. The blocks themselves will be moved to 'checked' blocks before reaching this though, not sure what effect the quorum has in that case.

**Comment by AlexeyAB** [comment]
@renesq Thanks. 


1. There is already `online_weight_quorum = 50` in the default config, does it mean that any block will wait for voting of holders who have 50% of Nano `133 248 290 / 2` ?  https://github.com/nanocurrency/raiblocks/blob/1eec79902a4365847e849c7598c6a4cf758dc0c6/docker/node/config/live.json#L52

2. But if there will be 51% of Nano off-line, then no one block can't be `checked`?

3. Do you mean that any block always wait for voting, since there is by default `online_weight_quorum = 50` in the `config.json`? I thought that only conflicting blocks are waiting for voting. 

4. Or how can I requrest voting for my non-conflict transaction?

----

> The blocks themselves will be moved to 'checked' blocks before reaching this though, not sure what effect the quorum has in that case.

5. Are there several states of block?
* not checked
* checked - there is no conflicts
* quorum checked - there is quorum voted
* conflict - there is conflict

6. So until `block-cementing` is implemented there can be rolled-back any non-conflicting transaction in any time (because non-conflicting transaction doesn't request voting by default). Those. There is no time, through which we can consider a transaction to be deterministically confirmed (as in Byteball) or probabilistically confirmed (as in Bitcoin), therefore, we can not safely transfer large sums.

Even in the Bitcoin with probabilistically confirmation based on PoW, there are also `checkpoints` that are hardcoded in the sourcecode which we can use as deterministic confirmation: https://github.com/bitcoin/bitcoin/blob/1b2460bd5824170ab85757e35f81197199cce9d6/src/chainparams.cpp#L133-L152

7. Also, if there will be implemented block-cementing, the even if the nodes that own the amount necessary for the quorum were Hacked, they would brake only new non-cemented blocks. But currently, the Hacked quorum-nodes can brake whole Nano network.

8. What approach is planned to use for block-cementing, is it something like Atomic-mass as in Radix?

**Comment by Omarino99** [comment]
I think this is part of a larger problem. When you are syncing from zero you are always trusting a node. Because that node could make up the whole history of the ledger for zero cost. Therefore, when you are trying to sync from zero you should have the ability to choose within the node from which source you want to download the ledger. You could download the ledger from multiple sources you trust (even download just the head block for each account when possible), compare the different versions of the ledger and choose the version that is the most commonly shared. This I think is an effective approach in PoS based ledgers. In this way you would ideally be in the same state of every other node once synced, and go from there. From that point if a fork occurs you will see the voting happening in real time.

**Comment by brunoerg** [comment]
The `online_weight_quorum` is about the nodes rebroadcasters, isn't it @rkeene?

**Comment by zhyatt** [comment]
Related to #1303

**Comment by zhyatt** [comment]
Resolved with #1770 and #1801
