### ISSUE TITLE
Support Stratification of Nodes

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/nano-node#1092]
To improve the node operator experience and encourage more adoption we will support a stratification
of nodes.  This will provide benefits similar to sharding, without the significant drawbacks associated
with that for a ledger.

**Comment by alandefreitas** [comment]
How is this stratification of nodes related to shards? It seems that, no matter what consensus algorithm we use and no matter how much bandwidth transactions take, we cannot make the network process more transactions that the slowest validator without sharding. However, we still don't know of a sharding algorithm without blocks of transactions so that users can create credit receipts and deposits on different shards.

**Comment by udikantz** [comment]
whats up with this feature,
are we able to limit bandwidth of the nodes within the node it self?
I don't want to start with traffic shaping because it my drop packets and may create unexpected results...
the nano node is eating all my home network bandwidth

**Comment by dsiganos** [comment]
Too old and not a priority at the moment. Closing.
