### ISSUE TITLE
PoW Client Compute and Resend Work based on network load

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/nano-node#1336]
Follow up to #1298 

Update the work computation system on the node to increase and resend blocks with greater work based on the current network load and the likelyhood that the block will be processed.  This may be exposed to the user as an RPC knob.

**Comment by rkeene** [comment]
1. OpenCL + Work Peers
  2. Track Locally Generated Blocks from Generation to Confirmation, resubmit if not confirmed in some epsilon

**Comment by argakiig** [comment]
- [ ] calculate median active_transaction difficulty
- [ ] calculate work generation based on max(threshold, median active_transaction difficulty)

**Comment by guilhermelawless** [comment]
How will the cutoff point be decided for the node using the pre-computed work vs. computing new work with higher difficulty?

I'm thinking tracking other percentiles apart from the median might help in that decision.

**Comment by zhyatt** [comment]
@guilhermelawless Do you mean if a node has pre-computed work handy which is below the current median difficulty value, how will we decide whether to attempt using it vs. dumping it and computing a new higher value?

**Comment by guilhermelawless** [comment]
Exactly that, which is why I suggested tracking other percentiles.

Example to start the discussion. If the median difficulty has risen by 70% above the current precomputed work, should the node compute new work or not? Well, if we go check the 75th percentile difficulty and it is actually below our current work value, then it might not make sense to.

Just an idea to start the discussion. It doesn't look like something that will matter much, but incorrect tuning of parameters could lead to greedy nodes that are competing against each other in the event of a very high tx throughput.
