### ISSUE TITLE
URI standard for representative change

### ISSUE THREAD

**Issue by BitDesert** [nanocurrency/nano-node#1497]
We have already some standards for sending NANO to an address as described here: https://github.com/nanocurrency/raiblocks/wiki/URI-and-QR-Code-Standard

Wouldn't it be great if we have a standard for representatives as well? 
People would be able to click a link and their favorite wallet app would prefill everything for them.

As a standard I would suggest:

```
xrbrep:xrb_<encoded address>[?][label=<label>][&][message=<message>]
```

Where label would be the representatives name and message a optional message that the rep could provide (like a small thank you).

**Comment by renesq** [comment]
With Natrium wallet getting more popular (and also some others that support URIs) , I think that it's time to introduce a rep change URI. Especially because it doesn't require the NANO team to do much besides setting it as a standard. 

Also note that the URI documentation still uses the old xrb scheme. It's time for a change to nano.

**Comment by zhyatt** [comment]
Updated wiki documentation to reflect the move to `nano_` and add in `nanorep` standard: https://github.com/nanocurrency/nano-node/wiki/URI-and-QR-Code-Standard.
