### ISSUE TITLE
data_directory as VirtualBox shared folder causes program crash

### ISSUE THREAD

**Issue by noahc66260** [nanocurrency/nano-node#1975]
**Description of bug:**
When trying to use the --data_path option set to a Virtualbox shared folder, the program aborts. I also get the same results when I symlink the default data directory to the shared folder and don't specify the --data_path option.

**Steps to reproduce the issue:**
1. On Ubuntu 18.04 (host), set up a VirtualBox instance of Ubuntu 18.04 (guest)
2. Install guest additions to set up a shared folder.
3. download nano-node-18.0-Linux.tar.bz2
4. run ./nano_wallet --data_path=[path to shared folder]

**Describe the results you received:**
$ ./nano_wallet --data_path=/media/[virtualbox shared folder]
Assertion (status4 == 0) failed ../nano/node/lmdb.cpp:31
Aborted (core dumped)

**Describe the results you expected:**
The node software should have not crashed.

**Environment**:
- Ubuntu 18.04 (guest)
- Ubuntu 18.04 (host)
- (Linux) Kernel: Linux noah-VirtualBox 4.18.0-18-generic #19~18.04.1-Ubuntu SMP Fri Apr 5 10:22:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Node version: 18.0
- (docker node) docker version -- not applicable

**Logs**
No logs are generated.

**Comment by clemahieu** [comment]
The database we use, LMDB, memory-maps the file it uses. Searching around it looks like virtualbox shared folders doesn't support memory mapping files through their driver. https://www.virtualbox.org/pipermail/vbox-dev/2013-April/011349.html

Attaching storage to the VM via SCSI is an option, otherwise you'll have to find a connection method that supports memory mapping files.
