### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by tundak** [nanocurrency/nano-node#2068]
With RC3 RPC call `wallet_history` & `account_history` cause to Segmentation fault (core dumped)

**Comment by wezrule** [comment]
I just tried the `account_history` RPC (on master) and it worked ok.
What is the account you are using, could you supply the whole RPC command?
Are you able to locate the core dump? If so that would be useful for us. Alternatively can you run the node with: `gdb --args ./nano_node --daemon`
Then type `bt` after it crashes and report what it outputs.
