### ISSUE TITLE
Suggestion: Lift base/minimum difficulty for everyone on saturated network to mitigate spam

### ISSUE THREAD

**Issue by telcy** [nanocurrency/nano-node#2202]
If I understood it right the minimum difficulty does never change and that would make it quite easy for a spammer. I think we should lift the base/minimum difficulty as soon as the network becomes saturated.

What do you think?

**Comment by schenkty** [comment]
I don't think this is a good idea only because there is no way currently to build a node that understands what the saturation point is. From my findings, the saturation is not defined on the local level but rather the global level so you have some nodes that are under the saturation point while the majority of the rest are over the saturation point.

**Comment by zhyatt** [comment]
Closing out as Dynamic PoW already handles fluctuations in difficulty during heavy network load.
