### ISSUE TITLE
Node telemetry

### ISSUE THREAD

**Issue by zhyatt** [nanocurrency/nano-node#2225]
Provide methods for nodes to send various metrics between each other for better monitoring of network status and upgrades progress. Some metrics being considered:

- Block count
- Cemented block count
- Set bandwidth cap
- Protocol version number
- Node vendor version
- Peer counts

Are there any other metrics to consider for inclusion?

**Comment by wezrule** [comment]
Perhaps number of accounts

**Comment by schenkty** [comment]
@wezrule I assume you are referring to number of accounts in the node wallet? If so, I think it is a very slippery slope to include any wallet data. It may be too precautionary but anything along the lines of sending wallet data to peers could have a mistake at some point where private wallet data is leaked to a peer which concerns me.

**Comment by wezrule** [comment]
I am referring to the number of the accounts in the ledger

**Comment by schenkty** [comment]
@wezrule oh thank you. I was worried 😂

**Comment by arranHarty123** [comment]
Would bootstrap settings be useful? e.g. my node is not bootstrapping anyone, but will establish x bootstrap connections to catch up.

**Comment by zhyatt** [comment]
Related to #1308

**Comment by bryanwag** [comment]
It is crucial to have a reliable and objective way to measure node performance because the scalability of the network depends heavily on node hardware, yet we currently have to rely on rep's self-report and stress tests to even get a basic idea on that metric. This method is neither quantitative nor reliable. Thus, it's easy to game and hard to educate users on how to choose a rep that is beneficial to the network. 

If we allow each peer to report vote latency of other peers (time(Rep A vote arrives) - time(quorum reached)) and aggregate this result, with appropriate statistical modeling we can quantitatively and reliably measure the performance of reps.

I'm not a dev and not sure whether vote latency can/should be reported by peers within the node software. If this is the wrong place please let me know. Thanks!

**Comment by zhyatt** [comment]
Completed by #2446 and related tickets. Above suggestions captured in new issues: #2657 and #2658
