### ISSUE TITLE
MacOS wallet error: Too many open files

### ISSUE THREAD

**Issue by cenkalti** [nanocurrency/nano-node#2409]
**Description of bug:**

Wallet does not open on MacOS after a some blocks are downloaded.

**Steps to reproduce the issue:**
1. Open MacOS app
2. Wait for some time to download some of the blocks. (Downloaded ~27M blocks)
3. Close the app.
4. Open the app.

**Describe the results you received:**
Error presented and walled is closed. Error says: "Exception while running wallet: Too many open files" 
Screenshot:
![](https://d1czrtm2mp3lak.cloudfront.net/items/0j3n0B0b2k193C0e2I0S/Image%202019-11-18%20at%202.16.03%20PM.png)

**Describe the results you expected:**
Normal operation

**Additional information you deem important (e.g. issue happens only occasionally):**

**Environment**:

MacOS Catalina, Node V20.0

**logs**

Node log: https://gist.github.com/cenkalti/806072e381e66a0493589e66a8cd1a6f

**Comment by zhyatt** [comment]
@cenkalti This is a known issue with V19.0+. To help clarify, a new callout was added to the docs here: https://docs.nano.org/releases/node-releases/#current-release. Please see the workaround posted in the callout there and let us know if that doesn't resolve the issue on your end.

**Comment by cenkalti** [comment]
The solution at https://superuser.com/a/1171028 didn't work. It seems that my limits appear to be high enough:
```
$ sysctl kern.maxfiles
kern.maxfiles: 49152
$ sysctl kern.maxfilesperproc
kern.maxfilesperproc: 24576
```

**Comment by zhyatt** [comment]
@cenkalti Can you confirm you went through all the steps in the superuser article including restarting the system to make sure changes take hold? If so, we recommend running this and providing the debug files so we can investigate further: `lsof -p `ps -A | grep [n]ano_node | awk '{print$1}'` >~/debug_files`

**Comment by cenkalti** [comment]
Instead of manually changing the limits from terminal like I did before, putting a new launchd file as described in https://superuser.com/a/1171028 solved the problem. Nano wallet opened after loading the launchd file with `sudo launchctl load -w /Library/LaunchDaemons/...` command. My system didn't need a restart.

However, this solution is far from perfect for an app. The app should increase its own limits (if possible) or find a way to work with allowed limits.

**Comment by cryptocode** [comment]
@cenkalti right, the link has various solutions for various macOS versions, and new releases have a very conservative default (256). The app should ideally set this, but I'm not aware of a way to set the launchctl limits programmatically (ulimit and launchctl limits are separate). If anyone knows, please let us know. 

As far as I can tell, these limits are only imposed on the developer Qt wallet (because it's spawned through launchctl), not on a node daemon running on macOS.

If other people are trying various workarounds, here's a couple of easy commands to check if it worked:

`launchctl limit maxfiles`

`ulimit -a |grep descriptors`

**Comment by cryptocode** [comment]
See also https://github.com/nanocurrency/nano-node/issues/2153
