### ISSUE TITLE
A standardized node benchmarking routine?

### ISSUE THREAD

**Issue by qwahzi** [nanocurrency/nano-node#2875]
How difficult would it be to create a standardized local-node benchmarking routine (maybe a --local-benchmark flag)? 

In my case, I'm specifically curious about pure PR performance, no block creation/sending/propagation, just passive listening, processing, and outbound voting in perfect network conditions (i.e. not limited by other nodes/votes). How do I objectively compare the potential node performance of a 2 CPU, 2GB memory cloud node vs an 8 CPU 8GB memory node?

For example, the benchmark could run a set list of common node/RPC commands with fake (locally-generated) "blocks" and "votes" (instant response), just to measure how well a node might perform if network performance & other nodes weren't a bottleneck. Output-wise, it'd be great to see "Node A processed X blocks/second over Y seconds", with CPU/memory/disk IO stats included.

**Comment by guilhermelawless** [comment]
Difficult. There is functionality via CLI to profile some things like bootstrapping, work validation, signature generation, vote verification (sig checking), frontier search. Aditionally, there are some slow tests for confirmation height processing, ledger processing and others.

It would be possible to create a benchmark CLI that goes through some of the other profile functions and outputs the stats, but ultimately it's how all the functionality works together that matters. If you have a CPU with a low amount of physical cores, you might do great at each of those functions individually, but when they need to be performed simultaneously you'll see a performance loss. Furthermore, databases have higher performance when they're empty, so there would be a lengthy preparation phase to bring it to the same order of magnitude as the current ledger.

Benchmarking at that level is also problematic because it would involve spawning at the very least two nodes, which is not entirely realistic either. Another option would be to do a benchmark server/client that you can place in two different computers. We actually do this sometimes during development, but it falls short in terms of our complexity, which evolves non-linearly with the number of nodes on the network.

Beyond that, we start to approach the methods we've been using i.e. a beta network while trying to maintain similar conditions. We're also exploring other automated testing options, but for the reasons listed above, there isn't yet a benchmark routine that everyone can run locally as that would have some assumptions that lead to false conclusions.

**Comment by qwahzi** [comment]
Thank you for the detailed response, much appreciated!

You're right, I wouldn't want to run any of those CLI profiles in isolation, my hope was that there would be a way to essentially simulate all real node functions (simultaneously) under pseudo-saturation, but with fake (completely local) votes/blocks to simulate instant response/perfect network conditions. I run a beta node off and on, but I think that serves a slightly different purpose than what I'm looking for here

Even though a local saturation test would not truly reflect actual network performance, it seems like it would at least give us a starting point for more objective comparisons of different hardware combinations. For example, if I ran the routine on my cheap node and the output was "10,000 local blocks processed in 10.1 seconds", I could easily up the CPU and run it again to see how adding cores impacts local performance (e.g. "11,000 local blocks processed in 9 seconds". It allows us to eliminate network variables (other node performance) and gives node operators a way to optimize their node hardware/configuration based on "real" data

In any case, it seems like this would be difficult to build (and perhaps still not as realistic or as valuable as I was hoping), but maybe it's worth considering again in the far future? (if yall ever run out of other work to do hahaha) If not, feel free to close this issue :)

**Comment by qwahzi** [comment]
For future readers, @gr0vity-dev created Nano-Bench for this purpose:
https://github.com/gr0vity-dev/nano-bench
