### ISSUE TITLE
Nodes over a Load Balancer

### ISSUE THREAD

**Issue by jeanpablojp** [nanocurrency/nano-node#3070]
This is not a problem but actually a doubt about a node behavior under a Load Balance structure.

I wanted to put a a node in a load balance structure to run a payment gateway using nano, but reading the documentation sounds like impossible since i would have problems with the data folder.

Put the data folder in a external driver with multiple simultaneous access is safe?

Can anybody suggest a different aproach???

Thank you a lot.

**Comment by Srayman** [comment]
You can run 2 nodes independently as they are primarily just your way of communicating with the network.  What you would then need to load balance is the RPC endpoints.

RPC is just HTTP requests, so you could do a simple pass through load balancer setup that forwards requests to each of the nodes behind the load balancer or something more complex like using a proxy like here for example https://github.com/Joohansson/NanoRPCProxy

If you’re doing requests at high rates and might end up with sync issues between the nodes over the network then you’d have to look at using sticky sessions so multiple requests use the same node for a period of time, but otherwise things should sync between the 2 nodes across the network quick enough it shouldn’t be a concern.

That’s my 2 cents.

**Comment by zhyatt** [comment]
Closing as answered
