### ISSUE TITLE
Adaptive confirmation solicitor based on bandwidth limits

### ISSUE THREAD

**Issue by zhyatt** [nanocurrency/nano-node#3094]
When we go beyond bandwidth limits we're not only doing unnecessary work by constructing confirmation requests / trying to broadcast blocks, but also there is no feed back process to inform the election that the request didn't go through. This means it's more likely the election will get escalated, since from the perspective of the election, requests are not getting replies.

@Srayman ran into this when bootstrapping from scratch with a 20Mbps limit, though our default 80Mbps doesn't run into it.

We could use the bandwidth limiter to get a long term sense of how many times the limit is hit and decrease (maybe in increments) the number of elections to request / broadcast from in each solicitor round.

This should also take into consideration the vote processor queue. More than 100 000 votes can be in the verification queue, plus the ones currently being processed, meaning we would take a very long time to process votes for our requests.

That means in this case we should not be soliciting votes if we already did it recently to that same channel (we currently re-do it every 5 seconds). Going that route might mean saving a set of representatives that we queried but haven't replied.

An easier route might be to reduce the soliciting rate according to the queue size and vote processing rate.

**Comment by zhyatt** [comment]
Related: https://github.com/nanocurrency/nano-node/issues/3095

**Comment by Srayman** [comment]
If my memory is accurate I think one of the biggest factors was the vote republishing that happens while bootstrapping, which results in a lot of outbound traffic.  Some of this has been alleviated by reducing the number of frontiers that are added every request loop which I think has slowed down the frontier confirmations some, though it's been a while since I've done a bootstrap and recorded stats.

PR nodes would also be less impacted by this since they do not republish other PR votes so their outbound bandwidth is a bit less in that regard than Non-PR nodes.

Otherwise the items mentioned look good, just wanted to add some additional details.

**Comment by qwahzi** [comment]
Resolved by the following ascending bootstrap PRs:

- https://github.com/nanocurrency/nano-node/pull/4211
- https://github.com/nanocurrency/nano-node/pull/4215
- https://github.com/nanocurrency/nano-node/pull/4205
- https://github.com/nanocurrency/nano-node/issues/3837
