### ISSUE TITLE
Critical Bug: Pending transactions never complete

### ISSUE THREAD

**Issue by damianof** [nanocurrency/nano-node#3263]
Inbound transaction from Kraken Hot Wallet show "confirmed" but funds never made it to the destination cold wallet here nano_394juhhmkeg9badbpambgt4bwst7mksatpythfxr3uuaboydwdup3mrx71gr:

https://nanocrawler.cc/explorer/block/6FF0057F42FD4059DD85CABFE40A2EB1AB86F0C24B6C4023D9614A1C1E17A3D3

Here you can see it showing Pending (it has been like this for days)
https://nanocrawler.cc/explorer/account/nano_394juhhmkeg9badbpambgt4bwst7mksatpythfxr3uuaboydwdup3mrx71gr/history

I checked also other outbound transaction from Kraken hot wallet and some of them have the same issue and show Pending for many days and seem to never get updated:
https://nanocrawler.cc/explorer/account/nano_3cpz7oh9qr5b7obbcb5867omqf8esix4sdd5w6mh8kkknamjgbnwrimxsaaf/history

**Comment by qwahzi** [comment]
This isn't a bug - the receiver (Kraken) has to broadcast a receive transaction. When you make a send transaction, the receiver has to create a corresponding receive transaction in order to be able to spend those funds. If they don't do that, the transaction stays pending indefinitely. In this case you'll probably have to reach out to Kraken, though they may be waiting until the V22 release to re-enable receives
