### ISSUE TITLE
Unit test `bulk.genesis_pruning` intermittently failing

### ISSUE THREAD

**Issue by zhyatt** [nanocurrency/nano-node#3519]
Not yet disabled

**Comment by theohax** [comment]
@zhyatt do you have a CI run when this failed? I've ran it many times on both Windows and Linux and I cannot get it to fail. I've also checked a bunch of recent and older CI runs and it was always green.

I'll try a more stressful approach when running the test, otherwise if still not failing I guess we can close it with non reproductible.

For the future, let's always add an URL to the failure when opening an issue about a test.

**Comment by zhyatt** [comment]
@theohax This issue was created at the request of @dsiganos so perhaps he can provide more context.

**Comment by dsiganos** [comment]
Duplicate of issue #3480
