### ISSUE TITLE
V27.1 too many unchecked blocks

### ISSUE THREAD

**Issue by twister65** [nanocurrency/nano-node#4732]
### Summary

Unchecked blocks increase but do not disappear.

### Node version

V27.1

### Build details

Manually built with no special options.

### OS and version

GNU/Linux 5.15.0-121-generic ~20.04.1-Ubuntu SMP

### Steps to reproduce the behavior

1.Start the node: nano_node --daemon
2.Wait and see unchecked blocks increasing
3.
...

### Expected behavior

Unchecked blocks are automatically cleared. No need to restart the node.

### Actual behavior

Unchecked blocks are not cleared.

**Comment by qwahzi** [comment]
Are you running RocksDB, have you had any node offline time recently, and/or are you bootstrapping from scratch? I believe there's at least one known issue related to missing bulk frontier scanning in the ascending bootstrapper (planned for V28), which can lead to a few missing accounts/blocks taking a while to get since the node is iterating through ~40M accounts:

https://github.com/nanocurrency/nano-node/issues/4346

**Comment by clemahieu** [comment]
The number of unchecked blocks fluctuates and may not always go to 0. Unless you've overridden it in your config it won't exceed 64k.
