### ISSUE TITLE
Reduce Bandwidth Utilization by Reducing Fanout

### ISSUE THREAD

**Issue by rkeene** [nanocurrency/nano-node#993]
Investigate whether the real-time network can be optimized by reducing fanout from a node when distributing messages.  Currently it may be sqrt(nodeCount) or 40+, it's not clear.  Validate that it's something reasonable and reduce it if it's not.

**Comment by rkeene** [comment]
Lee looked into this at a cursory level and indicated it may not be needed, let's confirm and close if no change is needed.

**Comment by zhyatt** [comment]
Dependent on https://github.com/nanocurrency/nano-node/issues/1548

**Comment by Srayman** [comment]
I’m curious what the plans are for this.  I’ve been experimenting with capturing vote traffic from the websocket to see the delay across different reps and noticed that for most reps I get 4-6+ messages per rep for each block hash from the websocket.

My assumption is each of the duplicates is from rebroadcasting votes, but curious to know if they could be from other actions like blocks being rebroadcast and causing another round of votes or something else etc.

I think the amount of extra traffic could be a significant impact on processing blocks and votes.  With the change to TCP it seems like packet loss should be significantly less and therefore rebroadcasting/fanout could be reduced some.

I don’t know the best structure to make it more efficient but one thought could be to setup a form of mesh, ring, star hybrid network to optimize how traffic is distributed.  I need to spend more time looking at the code to understand how the current process works for block and vote propagation, so if there any flow charts or workflows that exists that would be helpful.

Are there plans in the works or areas of data capture that would be helpful to evaluate this further?

**Comment by guilhermelawless** [comment]
Maybe a crazy idea, but nodes could auto-adjust fanout based on how many republishes they are receiving.

Not in terms of the number of peers, which is vulnerable to attacks of spawning idle nodes, but based on the actual messages they receive.

**Comment by qwahzi** [comment]
Should this issue be closed, due to age, it being partially addressed in [V21](https://github.com/nanocurrency/nano-node/pull/2468), and because there are a few more recent efforts in the same vein?:

Adjusting block rebroadcasting on arrival: https://github.com/nanocurrency/nano-node/issues/3419

Continuous backlog population: https://github.com/nanocurrency/nano-node/pull/3999

Adjusting vote broadcast intervals: https://github.com/nanocurrency/nano-node/pull/4010

Hinted elections redesign: https://github.com/nanocurrency/nano-node/pull/3944

Elections-Up branch: https://github.com/pwojcikdev/nano-node/tree/elections-up

> ![image](https://user-images.githubusercontent.com/3682613/211590076-a8ea2d50-ea85-49d9-a39b-5518e2d8c73e.png)

CC: @dsiganos
